name: ebt_flutter_elearning
description: "A modern, cross-platform eLearning app built with Flutter. This app provides interactive courses, quizzes, and progress tracking to enhance learning experiences across various subjects."
publish_to: 'none'
version: 1.0.0+1

# Evironment
environment:
  sdk: ^3.5.0

# Dependencies
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  dio: ^5.7.0
  provider: ^6.1.2
  google_sign_in: ^6.2.1
  get_it: ^7.7.0
  intl: ^0.19.0
  lottie: ^3.1.2

# Dev dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
